# Generated by Django 4.1.1 on 2022-09-20 20:43

from django.db import migrations


def update_additional_data_fields(apps, schema_editor):
    ForumUser = apps.get_model('userauth', 'ForumUser')
    for user in ForumUser.objects.all():
        user.bookmarks_count = user.additional_data.bookmarks_count
        user.bronze_badges = user.additional_data.bronze_badges
        user.silver_badges = user.additional_data.silver_badges
        user.gold_badges = user.additional_data.gold_badges
        user.last_email_datetime = user.additional_data.last_email_datetime
        user.next_badge = user.additional_data.next_badge
        user.people_reached = user.additional_data.people_reached
        user.posts_edited = user.additional_data.posts_edited
        user.search_count = user.additional_data.search_count
        user.votes = user.additional_data.votes
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('userauth', '0010_forumuser_bookmarks_count_forumuser_bronze_badges_and_more'),
    ]

    operations = [
        migrations.RunPython(update_additional_data_fields),

    ]
