# Generated by Django 4.2 on 2023-05-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Short name of badge', max_length=30, unique=True)),
                ('group', models.IntegerField(blank=True, default=None, help_text='For grouping badges with increasing criteria', null=True)),
                ('section', models.CharField(help_text='Section of this badge', max_length=30)),
                ('description', models.CharField(help_text='Description how a user can get this badge', max_length=300)),
                ('type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], help_text='Badge type', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('only_once', models.BooleanField(default=True, help_text='Can this badge be earned only once or more than once')),
                ('trigger', models.IntegerField(blank=True, choices=[(0, 'Upvote'), (1, 'Accept answer'), (2, 'Update post'), (3, 'Create post'), (4, 'View post'), (5, 'Edit profile'), (6, 'Create comment'), (7, 'Visit'), (8, 'Bookmark thread'), (9, 'Synonym approved'), (10, 'Tag edit'), (11, 'Tag created')], default=None, null=True)),
            ],
        ),
    ]
