# Generated by Django 4.2 on 2023-05-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('active', models.BooleanField(default=False, help_text='Is synonym active in searching for tags')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_word', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wiki', models.TextField(blank=True, default='')),
                ('number_of_questions', models.IntegerField(default=0, help_text='total number of questions with this tag asked')),
                ('number_asked_today', models.IntegerField(default=0, help_text='number of questions with this tag asked today')),
                ('number_asked_this_week', models.IntegerField(default=0, help_text='number of questions with this tag asked this week')),
                ('number_followers', models.IntegerField(default=0, help_text='Number of followers for tag, calculated async')),
                ('experts', models.CharField(blank=True, default='', help_text='Comma separated list of usernames that are considered experts', max_length=100, null=True)),
                ('stars', models.CharField(blank=True, default='', help_text='Comma separated list of usernames that are considered stars', max_length=100, null=True)),
                ('related', models.CharField(blank=True, default='', help_text='Comma separated list of related tags', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('summary', models.CharField(max_length=200)),
                ('before_wiki', models.TextField(blank=True, null=True)),
                ('before_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
