[tool.poetry]
name = "wiwik"
version = "0.1.0"
description = "What I wish I knew knowledge management system"
maintainers = ["Daniel Moran <daniel@moransoftware.ca>"]
authors = ["Daniel Moran <daniel@moransoftware.ca>"]
license = "Fair Source 50"
readme = "README.md"
packages = [
    { include = "forum" },
]

[tool.poetry.dependencies]
python = "^3.12"
Django = "^5.1"
django-allauth = { extras = ["socialaccount"], version = "^65.0.1" }

pyparsing = "^3.0"
python-dateutil = "^2.8"
sqlparse = "^0.5"
nltk = "^3.9"
#django-tasks-scheduler = "^3.0.0b2" # Async jobs scheduler using redis
django-admin-numeric-filter = "^0.1" # Django-admin filters
django-admin-rangefilter = "^0.13" # Django-admin filters
django-model-utils = "^5.0" # Django-admin filters
django-ipware = "^7.0" # For identifying IP location
geoip2 = "^4.8" # For identifying IP location
pillow = "^11" # For image field
scikit-learn = "^1.4" # For similarity TF-IDF
numpy = "^2.0" # For similarity TF-IDF

gunicorn = "^23.0" # Running configuration
python-dotenv = "^1.0" # Running configuration

# Frontend related
django-compressor = "^4.3"
django-crispy-forms = "^2.1"
crispy-bootstrap5 = "^2024.2"
markdown = "^3.4"
bleach = "^6.0"
pymdown-extensions = "^10.4"

# 3rd party integrations
slack-sdk = "^3.33"
meilisearch = "^0.32" # meilisearch driver
redis = "^5.0" # Redis driver, for redis-cache
psycopg = "^3.1"
django-constance = "^4.3"
django-tasks-scheduler ="^4.0.0b2"

[tool.poetry.group.dev.dependencies]
poetry = "^2.1"
ruff = "^0.11"
fakeredis = "^2.26"
coverage = "^7.6"
django-coverage-plugin = "^3"
beautifulsoup4 = "^4.12"
django-debug-toolbar = "^4.4"
db-to-sqlite = "^1.4"
behave-django = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
exclude = [
    '**/migrations/**',
    '__init__.py',
    '.venv/**',
    'private/**'
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"