# Generated by Django 4.2 on 2023-04-09 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("similarity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postsimilarity",
            options={"verbose_name_plural": "Similar Posts"},
        ),
    ]
