import os

SLACK_BOT_TOKEN = os.getenv('SLACK_BOT_TOKEN', None)
SLACK_NOTIFICATIONS_CHANNEL = os.getenv('SLACK_NOTIFICATIONS_CHANNEL', None)
SLACK_ADMIN_NOTIFICATIONS_CHANNEL = os.getenv('SLACK_ADMIN_NOTIFICATIONS_CHANNEL', None)
SLACK_SIGNING_SECRET_KEY = os.getenv('SLACK_SIGNING_SECRET_KEY', None)
