# Generated by Django 4.2 on 2023-05-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'verbose_name': 'Articles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('forum.question',),
        ),
    ]
