# Generated by Django 4.2 on 2023-04-09 15:14

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forum", "0008_alter_question_answers_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[],
            options={
                "verbose_name": "Articles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("forum.question",),
        ),
    ]
