# Generated by Django 4.2.7 on 2023-11-14 20:33

from django.db import migrations


def update_has_accepted_answer(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Article = apps.get_model("articles", "Article")
    for article in Article.objects.all():
        article.has_accepted_answer = True
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0002_alter_article_options'),
    ]

    operations = [
        migrations.RunPython(update_has_accepted_answer),
    ]
