# Generated by Django 4.0.6 on 2022-07-31 17:07

from django.db import migrations, models


def move_views_field(apps, schema_editor):
    Question = apps.get_model('forum', 'Question')
    for q in Question.objects.all():
        q.views = q.additional_data.views
        q.answers_count = q.answer_set.count()
        q.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0001_squashed_0007_question_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('q', 'Question'), ('a', 'Article')], default='q', help_text='Post type',
                                   max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(move_views_field, do_nothing),
    ]
