# Generated by Django 4.0.6 on 2022-07-31 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_question_answers_count_question_type_question_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionadditionaldata",
            name="views",
        ),
    ]
