# Generated by Django 4.1.7 on 2023-02-16 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0005_question_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
