# Generated by Django 4.1.7 on 2023-03-29 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0007_alter_questionview_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answers_count",
            field=models.IntegerField(default=0, help_text="Count number of answers"),
        ),
        migrations.AlterField(
            model_name="question",
            name="has_accepted_answer",
            field=models.BooleanField(default=False, help_text="Does post have an accepted answer?"),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_anonymous",
            field=models.BooleanField(default=False, help_text="Is post anonymous?"),
        ),
        migrations.AlterField(
            model_name="question",
            name="last_activity",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When was last activity created",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Link to post source in its originating platform",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("slack", "Slack"), ("teams", "Microsoft Teams")],
                help_text="Post source platform (slack, etc.)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="source_id",
            field=models.CharField(
                blank=True,
                help_text="id in the source platform",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="space",
            field=models.ForeignKey(
                blank=True,
                help_text="Space post is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spaces.space",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("a", "Open"),
                    ("t", "Triaged"),
                    ("c", "Closed"),
                    ("d", "Duplicate"),
                    ("h", "Hidden"),
                    ("O", "Off Topic"),
                    ("N", "Needs details or Clarity"),
                ],
                default="a",
                help_text="Post status",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(help_text="Tags post is asscociated with", to="tags.tag"),
        ),
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(help_text="Post title", max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[("q", "Question"), ("a", "Article"), ("h", "How to")],
                default="q",
                help_text="Post type",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="views",
            field=models.IntegerField(default=0, help_text="Number of views for post"),
        ),
    ]
