# Generated by Django 4.2.5 on 2023-09-09 14:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0008_alter_question_answers_count_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuestionInviteToAnswer",
            new_name="PostInvitation",
        ),
        migrations.AlterModelOptions(
            name="postinvitation",
            options={"verbose_name_plural": "Post Invitations"},
        ),
    ]
