# Generated by Django 4.2.5 on 2023-10-01 20:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('forum', '0010_alter_question_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagFollow',
            new_name='UserTagStats',
        ),
    ]
