# Generated by Django 4.2.5 on 2023-10-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_rename_tagfollow_usertagstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionFollow',
        ),
    ]
