# Generated by Django 5.0.3 on 2024-03-20 13:59

from django.db import migrations, models


def forwards(apps, schema_editor):
    activity_model = apps.get_model("forum", "VoteActivity")

    qs = activity_model.objects.all()
    for activity in qs:
        if activity.badge is not None:
            activity.type = "b"
        elif activity.reputation_change < 0:
            activity.type = "d"
        elif activity.reputation_change == 15:
            activity.type = "a"
        elif activity.reputation_change == 10:
            activity.type = "u"
        activity.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0014_alter_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteactivity",
            name="type",
            field=models.CharField(
                choices=[
                    ("u", "Upvote"),
                    ("d", "Downvote"),
                    ("a", "Accept answer"),
                    ("b", "Badge"),
                ],
                default="u",
                help_text="Vote activity type",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="status_updated_at",
            field=models.DateTimeField(
                blank=True, help_text="When was the status last updated", null=True
            ),
        ),
        migrations.RunPython(
            code=forwards,
            reverse_code=do_nothing
        ),
    ]
