# Generated by Django 5.0.4 on 2024-04-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_voteactivity_type_alter_question_status_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteactivity',
            name='type',
            field=models.CharField(choices=[('u', 'Upvote'), ('d', 'Downvote'), ('a', 'Accepted answer'), ('e', 'Edited post'), ('o', 'Accepted answer for old question'), ('b', 'Badge')], default='u', help_text='Vote activity type', max_length=2),
        ),
    ]
